// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VenteVehicule.Models;

#nullable disable

namespace VenteVehicule.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VenteVehicule.Models.Annonce", b =>
                {
                    b.Property<int>("id_annance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_annance"));

                    b.Property<DateTime>("DateMiseEnLigne")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTelephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Prix")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Vendeur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_Vehicule")
                        .HasColumnType("int");

                    b.HasKey("id_annance");

                    b.HasIndex("id_Vehicule");

                    b.ToTable("Annonces", (string)null);

                    b.HasData(
                        new
                        {
                            id_annance = 1,
                            DateMiseEnLigne = new DateTime(2023, 8, 5, 22, 33, 40, 166, DateTimeKind.Local).AddTicks(1132),
                            Description = "Belle voiture d'occasion à vendre.",
                            Email = "jean.dupont@example.com",
                            ImageURL = "https://example.com/images/car1.jpg",
                            NumeroTelephone = "123-456-7890",
                            Prix = 15000.00m,
                            Vendeur = "Jean Dupont",
                            id_Vehicule = 1
                        },
                        new
                        {
                            id_annance = 2,
                            DateMiseEnLigne = new DateTime(2023, 7, 31, 22, 33, 40, 166, DateTimeKind.Local).AddTicks(1137),
                            Description = "Voiture familiale spacieuse en bon état.",
                            Email = "alice.martin@example.com",
                            ImageURL = "https://example.com/images/car2.jpg",
                            NumeroTelephone = "987-654-3210",
                            Prix = 18000.00m,
                            Vendeur = "Alice Martin",
                            id_Vehicule = 2
                        },
                        new
                        {
                            id_annance = 3,
                            DateMiseEnLigne = new DateTime(2023, 8, 10, 22, 33, 40, 166, DateTimeKind.Local).AddTicks(1141),
                            Description = "Véhicule économique idéal pour la ville.",
                            Email = "cedric.anderson@example.com",
                            ImageURL = "https://example.com/images/car3.jpg",
                            NumeroTelephone = "555-123-4567",
                            Prix = 40000.00m,
                            Vendeur = "Cedric Anderson",
                            id_Vehicule = 3
                        });
                });

            modelBuilder.Entity("VenteVehicule.Models.VehiculeDoccasion", b =>
                {
                    b.Property<int>("id_vehicule")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_vehicule"));

                    b.Property<int>("AnneFab")
                        .HasColumnType("int");

                    b.Property<string>("Carburant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Couleur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateMiseEnVente")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kilometrage")
                        .HasColumnType("int");

                    b.Property<string>("Marque")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modele")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Prix")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_vehicule");

                    b.ToTable("VehiculeDoccasions", (string)null);

                    b.HasData(
                        new
                        {
                            id_vehicule = 1,
                            AnneFab = 2020,
                            Carburant = "Essence",
                            Couleur = "Bleu",
                            DateMiseEnVente = new DateTime(2023, 7, 16, 22, 33, 40, 166, DateTimeKind.Local).AddTicks(982),
                            Description = "Bonne condition, faible kilométrage.",
                            Kilometrage = 15000,
                            Marque = "Toyota",
                            Modele = "Corolla",
                            Prix = 15000.00m,
                            Transmission = "Automatique"
                        },
                        new
                        {
                            id_vehicule = 2,
                            AnneFab = 2018,
                            Carburant = "Essence",
                            Couleur = "Rouge",
                            DateMiseEnVente = new DateTime(2023, 7, 31, 22, 33, 40, 166, DateTimeKind.Local).AddTicks(1031),
                            Description = "Économique et fiable.",
                            Kilometrage = 20000,
                            Marque = "Honda",
                            Modele = "Civic",
                            Prix = 18000.00m,
                            Transmission = "Manuelle"
                        },
                        new
                        {
                            id_vehicule = 3,
                            AnneFab = 2022,
                            Carburant = "Essence",
                            Couleur = "Noir",
                            DateMiseEnVente = new DateTime(2023, 7, 1, 22, 33, 40, 166, DateTimeKind.Local).AddTicks(1034),
                            Description = "Voiture de sport puissante.",
                            Kilometrage = 1000,
                            Marque = "Ford",
                            Modele = "Mustang",
                            Prix = 40000.00m,
                            Transmission = "Automatique"
                        });
                });

            modelBuilder.Entity("VenteVehicule.Models.Annonce", b =>
                {
                    b.HasOne("VenteVehicule.Models.VehiculeDoccasion", "VehiculeDoccasion")
                        .WithMany("Annonces")
                        .HasForeignKey("id_Vehicule")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehiculeDoccasion");
                });

            modelBuilder.Entity("VenteVehicule.Models.VehiculeDoccasion", b =>
                {
                    b.Navigation("Annonces");
                });
#pragma warning restore 612, 618
        }
    }
}
